import { useState } from "react";
import { ApiError, applyImport, mapImport, previewImport, uploadImport } from "../../services/api";
type ImportField = "email" | "displayName" | "initialPassword" | "remoteAccessId" | "location" | "hardware";
type Outcome = { row: number; email?: string; outcome: "created" | "updated" | "rejected"; reason?: string; initialPassword?: string };
const fields: ImportField[] = ["email", "displayName", "initialPassword", "remoteAccessId", "location", "hardware"];
export function ImportPage() { const [id,setId]=useState(""); const [columns,setColumns]=useState<string[]>([]); const [mapping,setMapping]=useState<Record<string,ImportField | "">>({}); const [outcomes,setOutcomes]=useState<Outcome[]>([]); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const run=async (work:()=>Promise<void>)=>{setBusy(true);setError("");try{await work();}catch(e){setError(e instanceof ApiError?e.message:e instanceof Error?e.message:"Import request failed");}finally{setBusy(false);}};
  const upload=(file?: File)=>run(async()=>{if(!file)return;const r=await uploadImport(file);setId(r.importId);setColumns(r.columns);setOutcomes([]);setMessage("Map the spreadsheet columns, then preview.");});
  const preview=()=>run(async()=>{await mapImport(id,Object.fromEntries(Object.entries(mapping).filter(([,v])=>v)) as Record<string,ImportField>);const r=await previewImport(id);setOutcomes(r.outcomes as Outcome[]);setMessage("Review the row outcomes before applying.");});
  const apply=()=>run(async()=>{const r=await applyImport(id) as { outcomes: Outcome[] };setOutcomes(r.outcomes);setMessage("Import applied. Per-row outcomes are shown below.");});
  return <main className="mx-auto max-w-4xl p-6"><h1 className="text-2xl font-semibold">Import users</h1><p className="mt-1 text-sm text-gray-600">Upload, map, preview, then apply. Nothing changes before apply.</p><label className="mt-6 block text-sm font-medium">Excel workbook<input disabled={busy} className="mt-2 block" type="file" accept=".xlsx" onChange={e=>upload(e.target.files?.[0])}/></label>{columns.length>0&&<section className="mt-6 rounded border p-4"><h2 className="font-semibold">Column mapping</h2>{columns.map(c=><label key={c} className="mt-3 flex items-center gap-3 text-sm">{c}<select disabled={busy} value={mapping[c]??""} onChange={e=>setMapping({...mapping,[c]:e.target.value as ImportField | ""})}><option value="">Ignore</option>{fields.map(f=><option key={f} value={f}>{f}</option>)}</select></label>)}<button disabled={busy} className="mt-5 rounded bg-blue-600 px-4 py-2 text-white disabled:opacity-50" onClick={preview}>{busy?"Working…":"Preview"}</button></section>}{outcomes.length>0&&<section className="mt-6"><h2 className="font-semibold">Applied outcomes</h2><table className="mt-2 w-full text-left text-sm"><tbody>{outcomes.map(o=><tr key={o.row} className="border-b"><td className="p-2">{o.row}</td><td>{o.email}</td><td><span className="rounded bg-gray-100 px-2 py-0.5">{o.outcome}</span></td><td>{o.reason??o.initialPassword??""}</td></tr>)}</tbody></table><button disabled={busy} className="mt-5 rounded bg-emerald-700 px-4 py-2 text-white disabled:opacity-50" onClick={apply}>{busy?"Applying…":"Apply import"}</button></section>}{error&&<p role="alert" className="mt-5 text-red-700">{error}</p>}{message&&<p className="mt-5" role="status">{message}</p>}</main>; }
