import { useEffect, useState, type FormEvent } from "react";
import { getMyProfile, updateMyProfile } from "../services/api";
import type { RemoteAccessId, SupportProfile } from "../lib/types";

const empty: SupportProfile = { remoteAccessIds: [], location: "", hardware: "", staffEntries: [] };
export function ProfilePage() {
  const [profile, setProfile] = useState<SupportProfile>(empty); const [error, setError] = useState<string>(); const [saving, setSaving] = useState(false);
  useEffect(() => { getMyProfile().then(({ profile }) => setProfile({ ...profile, remoteAccessIds: profile.remoteAccessIds.length ? profile.remoteAccessIds : [{ tool: "Remote access", id: "" }] })).catch((e: unknown) => setError(e instanceof Error ? e.message : "Unable to load profile")); }, []);
  const changeAccess = (index: number, key: keyof RemoteAccessId, value: string) => setProfile((current) => ({ ...current, remoteAccessIds: current.remoteAccessIds.map((entry, i) => i === index ? { ...entry, [key]: value } : entry) }));
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setError(undefined); try { const result = await updateMyProfile({ remoteAccessIds: profile.remoteAccessIds.filter((entry) => entry.tool.trim() && entry.id.trim()), location: profile.location, hardware: profile.hardware }); setProfile(result.profile); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save profile"); } finally { setSaving(false); } }
  return <main className="mx-auto max-w-md p-6"><h1 className="text-xl font-semibold">Support profile</h1><p className="mt-1 text-sm text-gray-500">These details help IT staff assist you when a case needs escalation.</p><form onSubmit={save} className="mt-5 flex flex-col gap-4"><fieldset><legend className="text-sm">Remote access IDs</legend>{profile.remoteAccessIds.map((entry, index) => <div key={index} className="mt-2 flex gap-2"><input aria-label={`Remote access tool ${index + 1}`} className="min-w-0 rounded border border-gray-300 px-3 py-2" value={entry.tool} placeholder="Tool" onChange={(e) => changeAccess(index, "tool", e.target.value)} /><input aria-label={`Remote access ID ${index + 1}`} className="min-w-0 rounded border border-gray-300 px-3 py-2" value={entry.id} placeholder="ID" onChange={(e) => changeAccess(index, "id", e.target.value)} /><button type="button" className="text-sm text-red-700" onClick={() => setProfile((p) => ({ ...p, remoteAccessIds: p.remoteAccessIds.filter((_, i) => i !== index) }))}>Remove</button></div>)}<button type="button" className="mt-2 text-sm font-medium text-blue-600" onClick={() => setProfile((p) => ({ ...p, remoteAccessIds: [...p.remoteAccessIds, { tool: "", id: "" }] }))}>Add remote access ID</button></fieldset><label className="flex flex-col gap-1 text-sm">Location<input className="rounded border border-gray-300 px-3 py-2" value={profile.location} onChange={(e) => setProfile((p) => ({ ...p, location: e.target.value }))} /></label><label className="flex flex-col gap-1 text-sm">Device or asset details<textarea className="rounded border border-gray-300 px-3 py-2" value={profile.hardware} onChange={(e) => setProfile((p) => ({ ...p, hardware: e.target.value }))} /></label>{error && <p role="alert" className="text-sm text-red-600">{error}</p>}<button disabled={saving} className="rounded bg-blue-600 px-3 py-2 text-sm font-medium text-white disabled:opacity-50">{saving ? "Saving…" : "Save profile"}</button></form>{profile.staffEntries.length > 0 && <section className="mt-8"><h2 className="font-semibold">Staff notes and corrections</h2><ul className="mt-2 divide-y rounded border border-gray-200">{profile.staffEntries.map((entry, i) => <li key={`${entry.at}-${i}`} className="p-3 text-sm"><p>{entry.value}</p><p className="mt-1 text-xs text-gray-500">{entry.kind} by {entry.staffName} · {new Date(entry.at).toLocaleString()}</p></li>)}</ul></section>}</main>;
}
